### ISSUE TITLE
API 2.0: Items

### ISSUE THREAD

**Issue by dbouwman** [dbouwman/esri-portal-api#3]
# Version 2.0 Goals
- ES2015 all the things
- support for node _and_ browsers
- refactor so we don't have to pass in the token to all the functions
# Questions:
## Namespacing

Thoughts on having all this tied up in an `ArcGIS` namespace? Any value or just clutter? I'm leaning clutter...

First version had namespacing to match the AGO uri spaces... content & community etc. Seems like un-necessary abstractions leaking up. On the upside, mirroring that structure meant you could look for things in places similar to where the api had them.
## This repo / package?

This is a major breaking change in API and philosophy. The current version is simple promise sugar over the portal api, and expects the developer to work with the returned json. 

The new version would be oriented around building out classes with behavior, that persist themselves to the Portal API. Given the nature of the Portal API itself, it's not entirely clear that we can avoid nuances of the underlying API "leaking" up through this abstraction. Hence this "design in code" exercise
## Challenges
- The backing API is not entity-oriented
- some operations use different uri's depending on ownership of the resource the call is related to (i.e. sharing an item). To make the correct determination, the library needs to know more about the user we are acting on behalf of than simply their token.
## Instantiation

Create a portal instance. 
AuthInfo would be optional, but if not present, more parts of the api will return 403s etc.
By default the Portal will point to ArcGIS.com, but passing in a portalRootUrl property would override that.

```
var portal = new Portal({
    portalRootUrl:'https://qaext.arcgis.com',
    authInfo: {
          username:'dbouwman', 
           token:'MYTOKEN'
    }
});
```
### Search for Items

If the portal instance was passed authInfo, that will be used.

```
portal.items.search({...hash of params...}).then(...)
```
### List Items

The api requires a username for this request, so this will throw if the Portal does not have authInfo

```
portal.items.list({page:10,num:32}).then(...)
```
### Get an Item

Will throw with a 400 if the item is not public or the auth'd user can not access it

```
portal.items.get('abc123').then(...)
```
### Editing Item Properties

I don't think we should try to provide validation in this library - the underlying API should do this, and the options are so varied it would be hard to do.

Properties should be directly editable

```
myItem.title = 'some new title';
```

Properties can also be set via a hash

```
myItem.update({title:'some new title', description: 'some new description',...});
```

This module is primarily seen as a _component_ of a data-access layer, and as such does not handle anything related to mutation notification. If observers etc are needed, a framework like Backbone/Angular/Ember should be used on top of this module.
### Share an Item

User can only share items they own to groups they are members of.
not sure if we should expose this api detail (signature) or simply expose
groups, and access (public | org | private)

```
item.share({everyone: true/false, org:true/false, groups:['3ef...',b34...']}).then(...);

//syntactically nice, but requires object.observe
item.access = 'org';
item.groups.push('3ef...');
item.groups.push('b34...');
item.save(); //knows to make the extra API calls
```

The latter would be nice, but it means we need to handle dirty-checking in the item model, and then know to call these other methods during the save cycle, which seems fraught with problems - i.e. the item updated because the user owns it, but they tried to share it with a group they are not a member of, and so that failed...
It would also mean that item.get('...') would need to fetch the groups, which is an extra call that's not normally needed. Recommend we go with `.share({hash})`
### Get Item Data

Primarily of use with webmaps in javascript clients, but this could return virtually anything. 
Options would be:
- only allow this on some types of items
- throw if the response is not text
- ??? open to ideas here
- JSAPI's [PortalItem](https://developers.arcgis.com/javascript/jsapi/portalitem-amd.html) exposes a `.dataUrl` property and lets the consumer decide what to do... may be a good way to side-step handling the possibly random content.

```
item.data().then(...)
```
### Get Item Metadata

In node we can use a library to convert metadata into json. However, that library is huge and we don't want to ship that to a browser. Not sure if we should expose the format option or just get it as xml, and node apps can convert it as needed.

Item instance will be returned from items.get(...).

```
item.metadata({format:"xml" | "json"} ).then(...)
```
### Get Item Groups

```
item.groups().then(...);
```
### Create an Item

This will require authentication
I lean towards the first version...

```
var item = new ArcGIS.Item(json, portal);
item.save().then(...)

// this seems like the abstraction is leaking the portal api upwards
Portal.items.create(json).then(...)
```
### Update an Item

This will require authentication.
If the item has a .data property, that should be saved as well.

```
item.save().then(...);
```
### Delete an item

Only owner or org admin can do this.

```
portal.items.delete('3ef').then(...)
```

**Comment by ajturner** [comment]
I also prefer treating things as objects when possible.

``` javascript
let portal = new ArcGIS.Portal({token: "...", url: "http://www.arcgis.com/..."});

let airQualityData = portal.items.search({q: "air", type:"layer"});
let epaAir = airQualityData[0];
epaAir.update({title:"EPA AirQuality"});
epaAir.save(); 

// could have been epaAir.update(..).then(save);
```

I'm curious if `yield` can help make the above appear sync when it's really async.

**Comment by dbouwman** [comment]
I like this - esp the idea of `.update()` taking a hash - as long as we can also expect to set properties directly like

```
epaAir.title = 'my new title';

epaAir.save()
.catch(function(err){
   //handle error
});
```

In harvesters I have Static (and Instance) `.save()` methods on Item, Group and Job. This is because there are some scenarios where it's overkill to instantiate an object to just set one property and then save it, AND things are happening in tight loops. 

I feel that sort of optimization may be unique to harvester type applications. For now, let's stick with Instance methods.

**Comment by dbouwman** [comment]
This is on hold. The immediate need was for an Ember app, and it turns out that what's needed for an Ember DataAdapter is more akin to what this project already is - a simple wrapper over the xhr calls.

Thus, in the near-term, the ES2015 version of this library will reside in the ember project, with a long-term vision towards extraction into a stand-alone ES2015 lib.
